import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";
import BootstrapClient from "@/components/BootstrapClient";

// Layout component imports
import Header from "@/components/Header";

/* Template CSS */
import "@/assets/css/style.css";

/* Lightbox CSS */
import "@/assets/lib/lightbox/css/lightbox.min.css";

/* Owl Carousel CSS */
import "@/assets/lib/owlcarousel/assets/owl.carousel.min.css";
import "@/assets/lib/owlcarousel/assets/owl.theme.default.min.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css"
				/>
			</head>

			<body>
				<div className="wrapper">
					<BootstrapClient />
					<Header />
					{children}
					{/* Load jQuery first */}
					<Script
						src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
						strategy="beforeInteractive"
					/>
					{/* Load your template JS */}
					<Script src="/assets/js/main.js" strategy="afterInteractive" />

					<Script
						src="/assets/lib/owlcarousel/assets/owl.carousel.min.js"
						strategy="afterInteractive"
					/>

					<Script
						src="/assets/lib/lightbox/js/lightbox.min.js"
						strategy="afterInteractive"
					/>
				</div>
			</body>
		</html>
	);
}
